### PR TITLE
Ruth Follows

### PR DESCRIPTION
**Pull request by maijapapaya**
@jaredh159 @Henderjay

### CODE REVIEW

**Comment by maijapapaya** [comment]
This is the preface through Ch. 2

**Review by Henderjay — CHANGES_REQUESTED** [review]
Hey Maija, this all looks good, except for Chapter 2 on the original, it appears you forgot to mark up the Chapter Synopsis. Also... your note said this was the preface and the first two chapters, but I didn't see the preface anywhere.🧐

**Comment by maijapapaya** [comment]
Oh gosh, I'm sorry, I scanned through the preface too fast I think, and missed the end. 🙃

**Comment by Henderjay** [comment]
looks good, merged!

**Pull request merged**
